### PR TITLE
Support to change ViewConfig in runtime

### PR DESCRIPTION
**Pull request by ClarkXP**
I added this feature because I need it when I change the MapType in runtime.

### CODE REVIEW

**Comment by pengrad** [comment]
So, lets do not touch `ViewConfig` class, as its only for xml or default settings. Lets move all setters to MapScaleView. 
`desiredWidth` is constant, we should use something natural like setWidth.
`setColor` is enough, no need to use setColorResId

**Comment by pengrad** [comment]
Sorry, i can't accept it this way.
You changed 3 files and added one dependency for just `setColor(int color)`

**Comment by ClarkXP** [comment]
I did the changes only to change color, soon I will do the pull request

**Comment by pengrad** [comment]
Supported in 1.1.0

**Pull request closed without merging**
